### PR TITLE
MNT: Rerender for R 3.6.1

### PR DESCRIPTION
**Pull request by h-vetinari**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Towards dependencies of [r-recommended](https://github.com/conda-forge/r-recommended-feedstock/blob/master/recipe/meta.yaml) with 3.6.1

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
Note: conda smithy has some issues right now, so I'm manually collecting and committing the data when it fails. Probably should wait with merging until <code>@<space/>conda-forge-admin, please rerender</code> does not complain anymore.

About the linter failure, I'm guessing this is about `{{native}}toolchain`? Interestingly, conda-forge/r-lattice-feedstock#4 had the same lint warning and was merged nevertheless.

**Comment by dpryan79** [comment]
The toolchain stuff was the normal way of doing things until recently.

**Comment by dpryan79** [comment]
@conda-forge-admin please rerender

**Comment by dpryan79** [comment]
@h-vetinari Can you rerender this with conda-smithy locally?

**Comment by h-vetinari** [comment]
> @dpryan79: @h-vetinari Can you rerender this with conda-smithy locally?

That's what I tried, but I keep running into conda-forge/conda-smithy#1107. Thanks for taking over. :)

**Comment by dpryan79** [comment]
The good news is that the migration has officially started (2 hours ago), so there's no need to do this manually anymore.

**Comment by h-vetinari** [comment]
Closing as superseded by #11.

**Pull request closed without merging**
